# config/default.yaml
defaults:
  - _self_ 
 # - override hydra/hydra_logging: disabled
 # - override hydra/job_logging: disabled

hydra:
  sweep:
    dir: ${oc.env:RUNDIR, ./runs}/hydra_runs/${now:%Y-%m-%d}
    subdir: ${hydra.job.name}
  run:
    dir: ${oc.env:RUNDIR, ./runs}/hydra_runs/${now:%Y-%m-%d}

experiment: "resource-efficient-cv"
remote_mlflow: False
num_worker: 4
seeds:
  - 0
  - 1
  # - 2
  # - 3
  # - 4
  # - 5
  # - 6
  # - 7
  # - 8
  # - 9
