# Dockerfile.mlflow

FROM python:3.9-slim

RUN pip install mlflow psutil prometheus-client boto3

EXPOSE 5000

VOLUME ["/mlflow", "/mlruns"]

CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000", "--backend-store-uri", "sqlite:///mlflow/mlflow.db", "--default-artifact-root", "/mlflow/artifacts"]