[client]
toolbarMode = "viewer"

[server]
enableStaticServing = true

[theme]
base = "dark"
primaryColor = "#007626"
secondaryBackgroundColor = "#4b4b4d"

font = "materialdesign"
baseFontSize = 16

[[theme.fontFaces]]
family = "materialdesign"
url = "app/static/fonts/MaterialDesign-Webfont/fonts/materialdesignicons-webfont.woff2"
style = "normal"
